global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert-rules.yaml"

scrape_configs:
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true

  - job_name: 'netflix-clone'
    static_configs:
      - targets: ['netflix-clone-svc.netflix.svc.cluster.local:3000']
